### ISSUE TITLE
Wrap multiple elements

### ISSUE THREAD

**Issue by florentb** [mrzmmr/rehype-wrap#4]
On the [rehype plugins](https://github.com/rehypejs/rehype/blob/main/doc/plugins.md#list-of-plugins) page, it is written: "wrap selected element**s** with a given element" while the current README says: "Select **an** element to be wrapped".

Current results seem to only wrap ONE element even if the `wrap.selector` is a multiple elements selector (tag, css classes). In this case, the first element is wrapped. Do you confirm?

In my case I want to wrap all `table` elements with a `div`. That would be a more generic and very useful behavior.

**Comment by mrzmmr** [comment]
As of now yes, only the first match is wrapped since [`require('hast-util-select').select`](https://github.com/syntax-tree/hast-util-select) is used. For your use case, wrapping all `table` elements, you can write a function to do that pretty easily with something like,

```js
const visit = require('unist-util-visit')
const { selectAll } = require('hast-util-select')
const parseSelector = require('hast-util-parse-selector')

const plugin = (options = { selector: 'table' }) => tree => {
    for (const match of selectAll(options.selector, tree)) {
        visit(tree, match, (node, i, parent) => {
            const wrapper = parseSelector('div')
            wrapper.children = [node]
            parent.children[i] = wrapper
        })
    }
}
```

hope that helps.

**Comment by zackangelo** [comment]
Leaving this here for anyone else that happens upon this issue: 

https://github.com/florentb/rehype-wrap-all
